sudo: required

language: python

services:
  - docker

before_install:
  - docker build -t bind docker/bind
  - docker run --name nameserver bind -d
  - docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' nameserver


python:
  - "2.7"
  - "3.4"
  - "3.5"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
  - python setup.py develop
# command to run tests
script: pytest